on:
  push:
    branches:
      - main

name: Build and deploy
jobs:
  build: 
    runs-on: self-hosted
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create back-end env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
            POSTGRES_USER: postgres
            POSTGRES_DB: students
            POSTGRES_PASSWORD: postgres
            NODE_ENV: prod
            POSTGRES_USER: postgres://postgres:postgres@postgres_projeto_db:5432/students
          directory: back-end/
          filename: .env
          fail_on_empty: true

      - name: Create front-end env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          REACT_APP_BASE_URL: http://ec2-54-172-0-67.compute-1.amazonaws.com/api
          directory: front-end/
          filename: .env
          fail_on_empty: true

      - name: Build
        run: docker-compose build

      - name: Run
        run: docker-compose down && docker-compose up -d
